docs: add error message hint when db push fails because of a prepared statement
This commit updates the error message when supabase db push fails to select migrations.

- If the error message contains "prepared statement" and "already exists", then the hint
suggests adding statement_cache_mode=describe to the connection string

Context:

I was seeing an error from supabase db push like:

```
Error: Error querying remote database: ERROR: prepared statement "lrupsc_1_0" already exists (SQLSTATE 42P05).
Try running supabase db remote set.
```

The error is thrown by the first conn.Query (which selects applied mgirations)

I found that the cause of this is in pgx and it's caused by having pgbouncer in Transaction mode,
which is the recommended mode in supabase docs for serverless:
https://supabase.com/docs/guides/database/connecting-to-postgres#transaction

This can be resolved without any code changes by adding statement_cache_mode=describe to the connection string:
https://github.com/jackc/pgx/issues/602#issuecomment-532236718